name: Tag Version

on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Check commit message
        id: check
        run: |
          title="${{ github.event.head_commit.message }}"
          regex="^docker\(deps\):\sbump\sgolang.+to\s([0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2})"
          if [[ $title =~ $regex ]]; then
            name="v${BASH_REMATCH[1]}"
            echo ::set-output name=TAG_NAME::${name}
            echo ::set-output name=PUSH_TAG::true
          fi

      - name: Tag Version
        uses: anothrNick/github-tag-action@1.38.0
        if: steps.check.outputs.PUSH_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_ACTION_TOKEN }}
          CUSTOM_TAG: ${{ steps.check.outputs.TAG_NAME }}
