name: CI

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

env:
  PUSH_TAG: false
  TAG_NAME: 'v0.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
          
      - name: Check commit message
        id: check
        run: |
          if [[ ${{ github.event.head_commit.message }} =~ ^docker\(deps\): bump golang.+to\s([0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}) ]]; then
            name = "v${BASH_REMATCH[1]}"
            ${{ env.PUSH_TAG = true }}
            ${{ env.TAG_NAME = name }}
          fi
          
      - name: Tag Version
        uses: anothrNick/github-tag-action@1.34.0
        if: env.PUSH_TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ env.TAG_NAME }}
